### ISSUE TITLE
(@mikojs/create-project) Add testing case to coverage

### ISSUE THREAD

**Issue by HsuTing** [mikojs/core#445]
Relative #442, #446

- [x] Rewrite server testing #448 
- [x] Add testing case to coverage #449 
- [x] (fail) Add lerna install in the lerna case #451 
- [x] Add website checking in @mikojs/create-project #452
